### ISSUE TITLE
공연 주최자가 글 작성 권한을 얻어서 공연 정보를 저장하고 싶습니다.

### ISSUE THREAD

**Issue by junmanbo** [hee-k/voyage#1]
## 공연 정보 저장

- 일반 유저가 아닌 공연 주최자가 글 작성 권한을 얻고 싶습니다.
- 공연 주최자가 권한을 얻어서 공연 정보를 DB에 저장하고 싶습니다.

**Comment by hee-k** [comment]
- 권한 관련 기능 구현 중 DB에 결함이 있는 것을 확인했습니다.
